%{

#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vector>
#include <string>
#include <map>
#include "part3_helpers.hpp"

#define DEBUG_PARSER 0

#ifdef __cplusplus
extern "C" {
#endif

#if defined(FLEX_SCANNER) || defined(FLEXPP_SCANNER)
extern int yylex_destroy(void);
#else
#define yylex_destroy() (0)
#endif

#ifdef __cplusplus
}
#endif

int printOperationalError (string err);
int printSemanticError(string err);

typedef yystype YYSTYPE;
extern int yylineno;
extern char* yytext;
int yylex(void);
void yyerror(const char *s);

// Global variables
extern Buffer* buffer;
extern map<string, Symbol> symbolTable;
extern map<string, Function> functionTable;
int currentScopeRegsNum = 3;
int currentScopeOffset = 0;
Type currentReturnType;
bool inVariadicFunction = false;
bool isVariadicArgument = false;
bool missing_return = true;

int current_variable_offset = 0;
int current_param_offset = -8;
vector<string> current_symbols;

%}

/*%union {
    yystype yystype;  // Use the struct isDefined in part3_helpers.hpp
}*/

/* Keywords and operators */
%token  INT FLOAT VOID
%token  RETURN WRITE READ
%token  WHILE IF THEN ELSE DO
%token  ASSIGN VA_ARG ELLIPSIS
%token  OR AND NOT
%token  ID INTEGERNUM REALNUM STRING_LITERAL RELOP ADDOP MULOP
%token  COMMA SEMICOLON LPAREN RPAREN LBRACE RBRACE COLON

/* Operator precedence and associativity */
%right ASSIGN
%right IF THEN ELSE
%left OR
%left AND
%left RELOP
%left ADDOP
%left MULOP
%right NOT
%left LPAREN
%left RPAREN
%left LBRACE
%left RBRACE
%left COLON
%left SEMICOLON

/* Non-terminal types
%type  PROGRAM FDEFS FUNC_DEC_API FUNC_DEF_API FUNC_ARGLIST
%type  DCL STLIST STMT ASSN_STMT LVAL CNTRL_STMT
%type  BEXP EXP CALL CALL_ARGS CALL_ARGLIST
%type  NUM VA_MATERIALISE BLK RETURN_STMT WRITE_STMT READ_STMT TYPE
%type  M N
%start PROGRAM*/

%%

PROGRAM:
    FDEFS
    {
        #if DEBUG_PARSER
        cerr << "PROGRAM: Finished parsing FDEFS." << endl;
        #endif
        // Backpatch function calls
        for(auto& func : functionTable) {
            buffer->backpatch(func.second.callingLines, func.second.startLineImplementation);
        }

        /*// Add HALT AFTER all functions
        buffer->emit("HALT");*/
    }
;

FDEFS:
    FDEFS FUNC_DEF_API BLK
    {
        #if DEBUG_PARSER
        cerr << "FDEFS: FDEFS FUNC_DEF_API BLK" << endl;
        #endif

        if (missing_return)
        {
            if ($2.type == void_t)
            {
                buffer->backpatch($3.nextList, buffer->nextQuad());
                // Emit RETRN at the end of the function
                buffer->emit("RETRN");
            }
            else
            {
                printSemanticError("Semantic error: missing return statement for function '" + $1.name + "'");
            }
        }

        // Initialize the relevant globals
        currentScopeRegsNum = 3;
        currentScopeOffset = 0;
        current_variable_offset = 0;
        current_param_offset = -8;
        missing_return = true;
        inVariadicFunction = false;

        symbolTable.clear();
        $2.paramTypes.clear();
    }
    | FDEFS FUNC_DEC_API
    {
        #if DEBUG_PARSER
        cerr << "FDEFS: FDEFS FUNC_DEC_API" << endl;
        #endif
    }
    | /* empty */ { }
;

FUNC_DEC_API:
    TYPE ID LPAREN RPAREN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "FUNC_DEC_API: TYPE ID LPAREN RPAREN SEMICOLON" << endl;
        #endif
        $$.name = $2.name;
        $$.type = $1.type;
        $$.quad = buffer->nextQuad(); // TODO: Is this correct?

        if (functionTable.find($2.name) != functionTable.end()) {
            Function& existingFunc = functionTable[$2.name];
            if (existingFunc.returnType != $1.type) {
                printSemanticError("conflicting return type for function declaration '" + $2.name + "'");
            }
            if (!existingFunc.paramTypes.empty()) {
                printSemanticError("conflicting parameter types for function declaration '" + $2.name + "'");
            }
        } else {
            Function newFunc;
            newFunc.returnType = $1.type;
            newFunc.startLineImplementation = -1;
            newFunc.indexNumVAParams = -1;
            newFunc.startIndexVAParams = -1;
            newFunc.isDefined = false; // Mark as NOT isDefined for declaration
            functionTable.insert(std::pair<string,Function>($2.name, newFunc));
        }
        symbolTable.clear();
        current_param_offset = -8;
    }
    | TYPE ID LPAREN FUNC_ARGLIST RPAREN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "FUNC_DEC_API: TYPE ID LPAREN M FUNC_ARGLIST RPAREN SEMICOLON" << endl;
        for (size_t i = 0; i < $4.paramTypes.size(); ++i) {
            cerr << "    Arg " << i << ": " << $4.paramIds[i] << " (type " << $4.paramTypes[i] << ")" << endl;
        }
        #endif
        $$.name = $2.name;
        $$.type = $1.type;
        $$.paramTypes = $4.paramTypes;
        $$.paramIds = $4.paramIds;
        $$.quad = buffer->nextQuad();

        if (functionTable.find($2.name) != functionTable.end()) {
            Function& existingFunc = functionTable[$2.name];
            if (existingFunc.returnType != $1.type) {
                printSemanticError("conflicting return type for function declaration '" + $2.name + "'");
            }
            if (existingFunc.paramTypes != $4.paramTypes) {
                printSemanticError("conflicting parameter types for function declaration '" + $2.name + "'");
            }
        } else {
            Function newFunc;
            newFunc.returnType = $1.type;
            newFunc.paramTypes = $4.paramTypes;
            newFunc.paramIds = $4.paramIds;
            newFunc.startLineImplementation = -1;
            newFunc.indexNumVAParams = -1;
            newFunc.startIndexVAParams = -1;
            newFunc.isDefined = false; // Mark as NOT isDefined for declaration
            functionTable.insert(std::pair<string,Function>($2.name, newFunc));
        }

        symbolTable.clear();
        current_param_offset = -8;
    }
    | TYPE ID LPAREN FUNC_ARGLIST COMMA ELLIPSIS RPAREN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "FUNC_DEC_API: TYPE ID LPAREN FUNC_ARGLIST COMMA ELLIPSIS RPAREN SEMICOLON" << endl;
        #endif
        $$.name = $2.name;
        $$.type = $1.type;
        $$.paramTypes = $4.paramTypes;
        $$.paramIds = $4.paramIds;
        $$.quad = buffer->nextQuad();

        if ($4.paramTypes.empty() || $4.paramTypes.front() != int_)
        {
            printSemanticError("missing or non-int last named parameter before '...'");
        }

        if (functionTable.find($2.name) != functionTable.end()) {
            Function& existingFunc = functionTable[$2.name];
            if (existingFunc.returnType != $1.type) {
                printSemanticError("conflicting return type for variadic function declaration '" + $2.name + "'");
            }
            if (existingFunc.paramTypes != $4.paramTypes) {
                printSemanticError("conflicting parameter types for variadic function declaration '" + $2.name + "'");
            }
        } else {
            Function newFunc;
            newFunc.returnType = $1.type;
            newFunc.paramTypes = $4.paramTypes;
            newFunc.paramIds = $4.paramIds;
            newFunc.startLineImplementation = -1;
            newFunc.indexNumVAParams = $4.paramTypes.size();
            newFunc.startIndexVAParams = newFunc.indexNumVAParams + 1;
            newFunc.isDefined = false; // Mark as NOT isDefined for declaration
            functionTable.insert(std::pair<string,Function>($2.name, newFunc));
        }

        symbolTable.clear();
        current_param_offset = -8;
    }
;

FUNC_DEF_API:
    TYPE ID LPAREN RPAREN
    {
        #if DEBUG_PARSER
        cerr << "FUNC_DEF_API: TYPE ID LPAREN RPAREN" << endl;
        #endif
        $$.name = $2.name;
        $$.type = $1.type;
        $$.quad = buffer->nextQuad();
        /*
        cerr << "--- FUNC_DEF_API Processing for function: " << $2.name << " ---" << endl;
        cerr << "Before functionTable.find('" << $2.name << "')" << endl;
        cerr << "functionTable.size(): " << functionTable.size() << endl; // DEBUG: Table size
        //cerr << "definedFunctions.size(): " << definedFunctions.size() << endl; // DEBUG: Set size
        */
        if ($2.name == "main" && $1.type != void_t) {
            printSemanticError("main function must return void");
        }

        if (functionTable.find($2.name) != functionTable.end()) {
            Function& existingFunc = functionTable[$2.name];
            #if DEBUG_PARSER
            cerr << "Function '" << $2.name << "' FOUND in functionTable." << endl;
            cerr << "existingFunc.startLineImplementation: " << existingFunc.startLineImplementation << endl;
            cerr << "existingFunc.defined: " << existingFunc.isDefined << endl; // DEBUG: defined flag value
            #endif

            if (existingFunc.returnType != $1.type) {
                printSemanticError("conflicting return type for function declaration '" + $2.name + "'");
            }
            if (existingFunc.isDefined == true) {
                #if DEBUG_PARSER
                cerr << "*** Redefinition check triggered! ***" << endl;
                #endif
                printSemanticError("2 redefinition of function '" + $2.name + "'");
            } else {
                #if DEBUG_PARSER
                cerr << "Function was declared, now defining." << endl;
                #endif
                existingFunc.startLineImplementation = buffer->nextQuad();
                existingFunc.isDefined = true;
                // Initialize parameter offsets
                current_param_offset = -8;
                for (size_t i = 0; i < $4.paramIds.size(); i++) {
                    symbolTable[$4.paramIds[i]].offset[currentScopeOffset] = current_param_offset;
                    current_param_offset -= 4;
                }
            }
        } else {
            #if DEBUG_PARSER
            cerr << "Function '" << $2.name << "' NOT found in functionTable. Creating new entry." << endl;
            #endif
            Function newFunc;
            newFunc.returnType = $1.type;
            newFunc.paramTypes = $4.paramTypes;
            newFunc.paramIds = $4.paramIds;
            newFunc.startLineImplementation = $$.quad;
            newFunc.isDefined = true; // Mark as isDefined when first isDefined!
            newFunc.indexNumVAParams = -1;
            newFunc.startIndexVAParams = -1;
            functionTable.insert(std::pair<string,Function>($2.name, newFunc));
            // Initialize parameter offsets
            current_param_offset = -8;
            for (size_t i = 0; i < $4.paramIds.size(); i++) {
                symbolTable[$4.paramIds[i]].offset[currentScopeOffset] = current_param_offset;
                current_param_offset -= 4;
            }
            #if DEBUG_PARSER
            cerr << "functionTable.size() AFTER insert: " << functionTable.size() << endl; // DEBUG: Table size after insert
            //cerr << "definedFunctions.size() AFTER insert: " << definedFunctions.size() << endl; // DEBUG: Set size after insert

            cerr << "New function '" << $2.name << "' added to functionTable." << endl;
            cerr << "newFunc.startLineImplementation set to: " << newFunc.startLineImplementation << endl;
            cerr << "functionTable['" << $2.name << "'].startLineImplementation: " << functionTable[$2.name].startLineImplementation << endl;
            #endif
        }
        #if DEBUG_PARSER
        cerr << "--- FUNC_DEF_API Processing END for function: " << $2.name << " ---" << endl;
        #endif

        missing_return = true;
    }
    | TYPE ID LPAREN FUNC_ARGLIST RPAREN
    {
        #if DEBUG_PARSER
        cerr << "FUNC_DEF_API: TYPE ID LPAREN FUNC_ARGLIST RPAREN" << endl;
        #endif
        $$.name = $2.name;
        $$.type = $1.type;
        $$.paramTypes = $4.paramTypes;
        $$.paramIds = $4.paramIds;
        $$.quad = buffer->nextQuad();

        if (functionTable.find($2.name) != functionTable.end()) {
            Function& existingFunc = functionTable[$2.name];
            if (existingFunc.returnType != $1.type) {
                printSemanticError("conflicting return type for function declaration '" + $2.name + "'");
            }
            if (existingFunc.isDefined == true) {
                printSemanticError("3 redefinition of function '" + $2.name + "'");
            } else {
                existingFunc.startLineImplementation = buffer->nextQuad();
                existingFunc.isDefined = true;
            }
        } else {
            Function newFunc;
            newFunc.isDefined = true;
            newFunc.returnType = $1.type;
            newFunc.paramTypes = $4.paramTypes;
            newFunc.paramIds = $4.paramIds;
            newFunc.indexNumVAParams = -1;
            newFunc.startIndexVAParams = -1;
            newFunc.startLineImplementation = buffer->nextQuad();
            functionTable.insert(std::pair<string,Function>($2.name, newFunc));
        }

        missing_return = true;
    }
    | TYPE ID LPAREN FUNC_ARGLIST COMMA ELLIPSIS RPAREN
    {
        #if DEBUG_PARSER
        cerr << "FUNC_DEF_API: TYPE ID LPAREN FUNC_ARGLIST COMMA ELLIPSIS RPAREN" << endl;
        #endif
        $$.name = $2.name;
        $$.type = $1.type;
        $$.paramTypes = $4.paramTypes;
        $$.paramIds = $4.paramIds;
        $$.quad = buffer->nextQuad();

        if ($4.paramTypes.empty() || $4.paramTypes.front() != int_)
        {
            printSemanticError("missing or non-int last named parameter before '...'");
        }

        if (functionTable.find($2.name) != functionTable.end()) {
            Function& existingFunc = functionTable[$2.name];
            if (existingFunc.returnType != $1.type) {
                printSemanticError("conflicting return type for function declaration '" + $2.name + "'");
            }
             if (existingFunc.isDefined) {
                printSemanticError("4 redefinition of function '" + $2.name + "'");
            } else {
                existingFunc.startLineImplementation = buffer->nextQuad();
                existingFunc.isDefined = true;
            }
        } else {
            Function newFunc;
            inVariadicFunction = true;
            isVariadicArgument = true;
            newFunc.isDefined = true;
            newFunc.returnType = $1.type;
            newFunc.paramTypes = $4.paramTypes;
            newFunc.paramIds = $4.paramIds;
            newFunc.indexNumVAParams = $4.paramTypes.size();
            newFunc.startIndexVAParams = newFunc.indexNumVAParams + 1;
            newFunc.startLineImplementation = buffer->nextQuad();
            functionTable.insert(std::pair<string,Function>($2.name, newFunc));
        }

        int num_va_params_index = $4.paramTypes.size() - 1;
        int num_va_params_offset = -8 - (4 * num_va_params_index);
        if (3 != currentScopeRegsNum)
        {
            printOperationalError("Something went wrong. VA num reg should be 3.");
        }
        ++currentScopeRegsNum;

        buffer->emit("COPYI I3 " + to_string(num_va_params_offset));

        inVariadicFunction = true;
        missing_return = true;
    }
;

FUNC_ARGLIST:
    FUNC_ARGLIST COMMA DCL
    {
        #if DEBUG_PARSER
        cerr << "FUNC_ARGLIST: FUNC_ARGLIST COMMA DCL" << endl;
        #endif
        #if DEBUG_PARSER
        cerr << "FUNC_ARGLIST: Processed argument list." << endl;
        for (size_t i = 0; i < $$.paramTypes.size(); ++i) {
            cerr << "    Arg " << i << ": " << $$.paramIds[i] << " (type " << $$.paramTypes[i] << ")" << endl;
        }
        #endif
        $$.paramTypes = $1.paramTypes;
        $$.paramIds = $1.paramIds;
        $$.quad = buffer->nextQuad();

        // Finish defining params.
        for (auto symbol_name : current_symbols)
        {
            $$.paramTypes.push_back($1.type);
            $$.paramIds.push_back(symbol_name);
            // Offset of the new variable from the frame base.
            symbolTable[symbol_name].offset[currentScopeOffset] = current_param_offset;
            current_param_offset -= 4;
        }
        current_symbols.clear();
    }
    | DCL
    {
        #if DEBUG_PARSER
        cerr << "FUNC_ARGLIST: DCL" << endl; // Add debug print here
        #endif
        $$.quad = buffer->nextQuad();

        // Finish defining params.
        for (auto iter = current_symbols.rbegin(); iter != current_symbols.rend(); ++iter)
        {
            string& symbol_name = *iter;
            $$.paramTypes.push_back($1.type);
            $$.paramIds.push_back(symbol_name);
            // Offset of the new variable from the frame base.
            symbolTable[symbol_name].offset[currentScopeOffset] = current_param_offset;
            current_param_offset -= 4;
        }
        current_symbols.clear();
    }
;

BLK:
    OPEN_SCOPE LBRACE STLIST M RBRACE CLOSE_SCOPE
    {
        #if DEBUG_PARSER
        cerr << "BLK: LBRACE STLIST M RBRACE" << endl; // Add debug print here
        #endif
        $$.quad = $2.quad;
        buffer->backpatch($2.nextList, $3.quad);
    }
;

OPEN_SCOPE:
    /* EPSILON */
    {
        ++currentScopeOffset;
        #if DEBUG_PARSER
        cerr << "Open scope " << currentScopeOffset << endl;
        #endif
    }
;

CLOSE_SCOPE:
    /* EPSILON */
    {
        #if DEBUG_PARSER
        cerr << "Close scope " << currentScopeOffset << endl;
        #endif
        for (auto& symbol : symbolTable)
        {
            symbol.second.type.erase(currentScopeOffset);
            symbol.second.offset.erase(currentScopeOffset);
            size_t new_depth = 0;
            for (auto& offset : symbol.second.offset)
            {
                if (offset.first > new_depth)
                {
                    new_depth = offset.first;
                }
            }
            symbol.second.depth = new_depth;
        }

        --currentScopeOffset;
    }

DCL:
    ID COLON TYPE
    {
        #if DEBUG_PARSER
        cerr << "DCL: ID COLON TYPE" << endl;
        #endif
        $$.name = $1.name;
        $$.type = $3.type;
        $$.quad = buffer->nextQuad();

        if (symbolTable.find($1.name) == symbolTable.end())
        {
            Symbol new_symbol;
            new_symbol.type[currentScopeOffset] = $3.type;
            new_symbol.depth = currentScopeOffset;
            symbolTable[$1.name] = new_symbol;
        }
        else if (symbolTable[$1.name].type.find(currentScopeOffset) != symbolTable[$1.name].type.end())
        {
            printSemanticError("redefinition of variable '" + $1.name + "'");
        }
        else
        {
            symbolTable[$1.name].type[currentScopeOffset] = $3.type;
            symbolTable[$1.name].depth = currentScopeOffset;
        }
        current_symbols.push_back($1.name);
    }
    | ID COMMA DCL
    {
        #if DEBUG_PARSER
        cerr << "ID COMMA DCL" << endl;
        #endif
        $$.name = $1.name;
        $$.type = $3.type;
        $$.quad = buffer->nextQuad();

        if (symbolTable.find($1.name) == symbolTable.end())
        {
            Symbol new_symbol;
            new_symbol.type[currentScopeOffset] = $3.type;
            new_symbol.depth = currentScopeOffset;
            symbolTable[$1.name] = new_symbol;
        }
        else if (symbolTable[$1.name].type.find(currentScopeOffset) != symbolTable[$1.name].type.end())
        {
            printSemanticError("redefinition of variable '" + $1.name + "'");
        }
        else
        {
            symbolTable[$1.name].type[currentScopeOffset] = $3.type;
            symbolTable[$1.name].depth = currentScopeOffset;
        }
        current_symbols.push_back($1.name);
    }
;

TYPE:
    INT
    {
        #if DEBUG_PARSER
        cerr << "TYPE: INT" << endl;
        #endif
        $$.type = int_;
        $$.quad = buffer->nextQuad();
    }
    | FLOAT
    {
        #if DEBUG_PARSER
        cerr << "TYPE: FLOAT" << endl;
        #endif
        $$.type = float_;
        $$.quad = buffer->nextQuad();
    }
    | VOID
    {
        #if DEBUG_PARSER
        cerr << "TYPE: VOID" << endl;
        #endif
        $$.type = void_t;
        $$.quad = buffer->nextQuad();
    }
;

STLIST:
    STLIST STMT
    {
        #if DEBUG_PARSER
        cerr << "STLIST: STLIST STMT" << endl;
        #endif
        //$$.quad = $1.quad;
        //buffer->backpatch($1.nextList, $2.nextList);
        //$$.nextList = $2.nextList;
        //$2.name = $$.name;
    }
    | /* empty */
    {
        #if DEBUG_PARSER
        cerr << "STLIST: empty" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        $$.nextList.clear();
    }
;

STMT:
    DCL SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "STMT: DCL SEMICOLON" << endl;
        #endif
        $$.quad = $1.quad;
        $$.type = $1.type;

        // Finish defining new symbols.
        for (auto symbol_name : current_symbols)
        {
            // Allocate space on the stack for the variable.
            buffer->emit("ADD2I I2 I2 4");
            // Offset of the new variable from the frame base.
            symbolTable[symbol_name].offset[currentScopeOffset] = current_variable_offset;
            current_variable_offset += 4;
        }
        current_symbols.clear();
    }
    | ASSN_STMT
    {
        #if DEBUG_PARSER
        cerr << "STMT: ASSN_STMT" << endl;
        #endif
    }
    | EXP SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "STMT: EXP SEMICOLON" << endl;
        #endif
    }
    | CNTRL_STMT M
    {
        #if DEBUG_PARSER
        cerr << "STMT: CNTRL_STMT" << endl;
        #endif
        buffer->backpatch($1.nextList, $2.quad);
    }
    | READ_STMT
    {
        #if DEBUG_PARSER
        cerr << "STMT: READ_STMT" << endl;
        #endif
    }
    | WRITE_STMT
    {
        #if DEBUG_PARSER
        cerr << "STMT: WRITE_STMT" << endl;
        #endif
    }
    | RETURN_STMT
    {
        #if DEBUG_PARSER
        cerr << "STMT: RETURN_STMT" << endl;
        #endif
    }
    | BLK
    {
        #if DEBUG_PARSER
        cerr << "STMT: BLK" << endl;
        #endif
    }
;

RETURN_STMT:
    RETURN EXP SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "RETURN_STMT: RETURN EXP SEMICOLON" << endl;
        #endif
        $$.quad = buffer->nextQuad();
        $$.type = $2.type;  // Use $$ to set the type

        if ($2.type == float_) {
            buffer->emit(string("STORF F" + to_string($2.RegNum) + " F1 -4"));  // Copy result to F0
        } else {
            buffer->emit(string("STORI I" + to_string($2.RegNum) + " I1 -4"));  // Copy result to I0
        }
        buffer->emit("RETRN");
        missing_return = false;
    }
    | RETURN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "RETURN_STMT: RETURN SEMICOLON" << endl;
        #endif
        $$.type = void_t;
        buffer->emit("RETRN");
        missing_return = false;
    }
;

WRITE_STMT:
    WRITE LPAREN EXP RPAREN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "WRITE_STMT: WRITE LPAREN EXP RPAREN SEMICOLON" << endl;
        #endif
        $$.quad = buffer->nextQuad();

        if ($3.type == float_) {
            buffer->emit(string("PRNTF F") + to_string($3.RegNum));
        } else if ($3.type == int_) {
            buffer->emit(string("PRNTI I") + to_string($3.RegNum));
        } else {
            printSemanticError("invalid type for write statement");
        }
    }
    | WRITE LPAREN STRING_LITERAL RPAREN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "WRITE_STMT: WRITE LPAREN STRING_LITERAL RPAREN SEMICOLON" << endl;
        #endif
        $$.quad = buffer->nextQuad();
        string str = $3.name;
        str = str.substr(1, str.length() - 2); // Remove surrounding quotes

        for (size_t i = 0; i < str.length(); i++) {
            if (str[i] == '\\') {
                // Handle escape sequences
                if (i+1 >= str.length()) break;
                i++; // Skip backslash

                switch(str[i]) {
                    case 'n':  // Newline
                        buffer->emit("PRNTC 10");
                        break;
                    case '"':  // Handle escaped quotes
                        buffer->emit("PRNTC 34");
                        break;
                    case 't': // tab
                        buffer->emit("PRNTC 9");
                        break;
                    default:   // Unknown escape
                        buffer->emit("PRNTC " + to_string((int)str[i]));
                }
            } else {
                // Regular character
                buffer->emit("PRNTC " + to_string((int)str[i]));
            }
        }
    }
;

READ_STMT:
    READ LPAREN LVAL RPAREN SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "READ_STMT: READ LPAREN LVAL RPAREN SEMICOLON" << endl;
        #endif

        // Get the symbol information for the variable being read
        Symbol& sym = symbolTable[$3.name];
        int offset = sym.offset[sym.depth];

        // Allocate a temporary register for the read value
        int tempReg = currentScopeRegsNum++;

        if (sym.type[sym.depth] == float_) {
            // Read a float value into a float register
            buffer->emit("READF F" + to_string(tempReg));

            // Convert I1 (frame pointer) to a float register
            int floatBaseReg = currentScopeRegsNum++;
            buffer->emit("CITOF F" + to_string(floatBaseReg) + " I1");

            // Store the float value in memory
            buffer->emit("STORF F" + to_string(tempReg) + " F" + to_string(floatBaseReg) + " " + to_string(offset));
        } else {
            // Read an integer value into an integer register
            buffer->emit("READI I" + to_string(tempReg));

            // Store the integer value in memory
            buffer->emit("STORI I" + to_string(tempReg) + " I1 " + to_string(offset));
        }
    }
;

ASSN_STMT:
    LVAL ASSIGN EXP SEMICOLON
    {
        #if DEBUG_PARSER
        cerr << "ASSN_STMT: LVAL ASSIGN EXP SEMICOLON" << endl;
        #endif
        //$$.quad = buffer->nextQuad();

        Symbol& sym = symbolTable[$1.name];
        Type lvalType = sym.type[sym.depth];
        Type expType = $3.type;

        // Check for void type errors
        if (lvalType == void_t || expType == void_t) {
            printSemanticError("void type in assignment");
        }

        // Check for implicit casting and report a semantic error
        if (lvalType != expType) {
            printSemanticError("incompatible type of argument '" + $1.name + "'");
        }


        // $$: 'LVAL' has a register pointing to that var's memory
        int dest_offset = sym.offset[sym.depth];
        int src_reg   = $3.RegNum;


        if (lvalType == float_) {
            // Convert I1 (base pointer) to a float register
            int floatBaseReg = currentScopeRegsNum++;
            buffer->emit("CITOF F" + to_string(floatBaseReg) + " I1");

            // Store the float value in memory
            buffer->emit("STORF F" + to_string(src_reg) + " F" + to_string(floatBaseReg) + " " + to_string(dest_offset));
        } else if (lvalType == int_) {
            // Store the integer value in memory
            buffer->emit("STORI I" + to_string(src_reg) + " I1 " + to_string(dest_offset));
        }
        $$.type = lvalType;
        $$.RegNum = $1.RegNum;
        }
;

LVAL:
    ID
    {
        #if DEBUG_PARSER
        cerr << "LVAL: ID" << endl;
        #endif
        $$.name = $1.name;
        $$.quad = buffer->nextQuad();

        if (symbolTable.find($1.name) == symbolTable.end()) {
            printSemanticError("undefined variable '" + $1.name + "'");
        }

        Symbol& sym = symbolTable[$1.name];

        if (sym.type.find(sym.depth) == sym.type.end()) {
            printSemanticError("undefined variable '" + $1.name + "' at current scope");
        }
        //$$.type = sym.type[sym.depth];
        //$$.RegNum = currentScopeRegsNum++;
        //buffer->emit("ADD2I I" + to_string($$.RegNum) + " I1 " +
        //            to_string(sym.offset[sym.depth]));
    }
;

CNTRL_STMT:
    IF BEXP THEN M STMT ELSE N M STMT
    {
        #if DEBUG_PARSER
        cerr << "CNTRL_STMT:  IF BEXP THEN M STMT N ELSE M STMT" << endl;
        #endif
        $$.quad = buffer->nextQuad();

        buffer->backpatch($2.trueList, $4.quad);
        buffer->backpatch($2.falseList, $8.quad);
		$$.nextList = merge<int>($5.nextList, $7.nextList);
		$$.nextList = merge<int>($$.nextList, $9.nextList);
		$5.nextList.clear();
		$9.nextList.clear();
		$7.nextList.clear();
    }
    | IF BEXP THEN M STMT
    {
        #if DEBUG_PARSER
        cerr << "CNTRL_STMT:  IF BEXP THEN M STMT" << endl;
        #endif
        buffer->backpatch($2.trueList, $4.quad);
		$$.nextList = merge<int>($2.falseList, $5.nextList);
		$2.falseList.clear();
		$5.nextList.clear();
    }
    | WHILE M BEXP DO M STMT
    {
		buffer->backpatch($3.trueList, $5.quad);
		buffer->backpatch($6.nextList, $2.quad);
		$$.nextList = $3.falseList;
		// Emit to buffer UJUMP command. After backpatch the addressed would be filled
		buffer->emit("UJUMP " + intToString($2.quad));
	}
;

BEXP:
    BEXP OR M BEXP
    {
        #if DEBUG_PARSER
        cerr << "BEXP: BEXP OR BEXP" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        buffer->backpatch($1.falseList, $3.quad);
		$$.falseList = $4.falseList;
		$$.trueList = merge($1.trueList, $4.trueList);
		$1.trueList.clear();
		$4.trueList.clear();
    }
    | BEXP AND M BEXP
    {
        #if DEBUG_PARSER
        cerr << "BEXP: BEXP AND BEXP" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        buffer->backpatch($1.trueList, $3.quad);
		$$.trueList = $4.trueList;
		$$.falseList = merge<int>($1.falseList, $4.falseList);
		$1.falseList.clear();
		$4.falseList.clear();
    }
    | NOT BEXP
    {
        #if DEBUG_PARSER
        cerr << "BEXP: NOT BEXP" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        $$.trueList = $2.falseList;
        $$.falseList = $2.trueList;
    }
    | EXP RELOP EXP
    {
        #if DEBUG_PARSER
        cerr << "BEXP: EXP RELOP EXP" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        if ($1.type != $3.type) {
            printSemanticError("type mismatch in relational expression");
            //return 1;
        } else if ($1.type == void_t) {
			printSemanticError("can't perform this operation on 'void' type arguments");
        }


        $$.RegNum = currentScopeRegsNum++;
        string opName;

        if ($2.name == "==")       opName = "SEQU";
        else if ($2.name == "<>")  opName = "SNEQ";
        else if ($2.name == "<=" || $2.name == ">")  opName = "SGRT"; 
        else if ($2.name == ">=" || $2.name == "<")  opName = "SLET"; 
        else printOperationalError("Invalid relative operator.");


        // Emit the compare instruction: we want I$.RegNum no matter float or int
    //int cmpFloatReg = -1;
    if ($1.type == float_) {
        int cmpFloatReg = currentScopeRegsNum++;
        // Compare floats => produce int in I$.RegNum
        buffer->emit(opName + "F F" + to_string(cmpFloatReg)
                     + " F" + to_string($1.RegNum)
                     + " F" + to_string($3.RegNum));

        buffer->emit("CFTOI I" + to_string($$.RegNum) +
                     " F" + to_string(cmpFloatReg));
    } else {
        // Compare ints => produce int in I$.RegNum
        buffer->emit(opName + "I I" + to_string($$.RegNum)
                     + " I" + to_string($1.RegNum)
                     + " I" + to_string($3.RegNum));
    }

    // Next line does the branch on that integer result
    // If the op is "==", for instance, the result is 1 or 0 in I$.RegNum

    $$.falseList.push_back(buffer->nextQuad());
    if ($2.name == "<>" || $2.name == "==" ||
        $2.name == "<"  || $2.name == ">")
    {
        // Branch if result==0
        buffer->emit("BREQZ I" + to_string($$.RegNum) + " ");
    }
    else {
        // Branch if result!=0
        buffer->emit("BNEQZ I" + to_string($$.RegNum) + " ");
        }

        $$.trueList.push_back(buffer->nextQuad());
        buffer->emit("UJUMP ");
    }
    | LPAREN BEXP RPAREN
    {
        #if DEBUG_PARSER
        cerr << "BEXP: LPAREN BEXP RPAREN" << endl;
        #endif
        //$$.quad = $2.quad;
        $$.trueList = $2.trueList;
        $$.falseList = $2.falseList;
    }
;

EXP:
    EXP ADDOP EXP
    {
        #if DEBUG_PARSER
        cerr << "EXP: EXP ADDOP EXP" << endl;
        #endif
        $$.quad = buffer->nextQuad();

        if ($1.type == void_t || $3.type == void_t) {
            printSemanticError("void type in arithmetic expression");
        }
        if ($1.type != $3.type)
        {
            printSemanticError("mismatch in types between arithmetic operators");
        }

        string regType = ($$.type == float_) ? "F" : "I"; 
        string opName = ($2.name == "+") ? "ADD2" : "SUBT"; 
        $$.type = $1.type;
        $$.RegNum = currentScopeRegsNum++;

        // Handle type conversions
        int reg1 = $1.RegNum;
        int reg2 = $3.RegNum;
        buffer->emit(opName + regType + " " + regType + to_string($$.RegNum) +
            " " + regType + to_string(reg1) +
            " " + regType + to_string(reg2));
    }
    | EXP MULOP EXP
    {
        #if DEBUG_PARSER
        cerr << "EXP: EXP MULOP EXP" << endl;
        #endif
        $$.quad = buffer->nextQuad();

        if ($1.type == void_t || $3.type == void_t) {
            printSemanticError("void type in arithmetic expression");
        }
        if ($1.type != $3.type)
        {
            printSemanticError("mismatch in types between arithmetic operators");
        }

        string regType = ($$.type == float_) ? "F" : "I";
        string opName = ($2.name == "*") ? "MULT" : "DIVD";
        $$.type = ($1.type == float_ || $3.type == float_) ? float_ : int_;
        $$.RegNum = currentScopeRegsNum++;

        // Handle type conversions
        int reg1 = $1.RegNum;
        int reg2 = $3.RegNum;
        buffer->emit(opName + regType + " " + regType + to_string($$.RegNum) +
            " " + regType + to_string(reg1) +
            " " + regType + to_string(reg2));
    }
    | LPAREN EXP RPAREN
    {
        #if DEBUG_PARSER
        cerr << "EXP: LPAREN EXP RPAREN" << endl;
        #endif
        $$ = $2;  // Pass through all attributes
    }
    | LPAREN TYPE RPAREN EXP
    {
        #if DEBUG_PARSER
        cerr << "EXP: LPAREN TYPE RPAREN EXP" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        if ($2.type == void_t && $4.type != void_t) {  
            printSemanticError("can't cast a non-void expression to void");
        } else if ($2.type != void_t && $4.type == void_t) {
            printSemanticError("can't perform this operation on 'void' type argument");
        }
        $$.type = $2.type;
        $$.RegNum = currentScopeRegsNum++;

        if ($2.type == float_ && $4.type == int_) {
            buffer->emit(string("CITOF F") + to_string($$.RegNum) + string(" I") + to_string($4.RegNum));
        } else if ($2.type == int_ && $4.type == float_) {
            buffer->emit(string("CFTOI I") + to_string($$.RegNum) + string(" F") + to_string($4.RegNum));
        } else {
            if ($2.type == float_) {
                buffer->emit(string("COPYF F") + to_string($$.RegNum) + string(" F") + to_string($4.RegNum));
            } else {
                buffer->emit(string("COPYI I") + to_string($$.RegNum) + string(" I") + to_string($4.RegNum));
            }
        }
    }
    | ID
    {
        #if DEBUG_PARSER
        cerr << "EXP: ID" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        
        if (symbolTable.find($1.name) == symbolTable.end()) {
            printSemanticError("unDefined variable '" + $1.name + "'");
        }

        Symbol& sym = symbolTable[$1.name];
        if (sym.type.find(sym.depth) == sym.type.end()) {
            printSemanticError("unDefined variable '" + $1.name + "' at current scope");
        }

        $$.type = sym.type[sym.depth];
        $$.RegNum = currentScopeRegsNum++;
        $$.name = $1.name;

        if ($$.type == float_) {
            int floatBaseReg = currentScopeRegsNum++;
            buffer->emit("CITOF F" + to_string(floatBaseReg) + " I1");  // Convert I1 to F
            buffer->emit("LOADF F" + to_string($$.RegNum) + " F" + to_string(floatBaseReg) + " " + to_string(sym.offset[sym.depth]));
        } else {
            buffer->emit(string("LOADI I") + 
                         to_string($$.RegNum) + string(" I1 ") +
                         to_string(sym.offset[sym.depth]));
        }
    }       
    | NUM
    {
        #if DEBUG_PARSER
        cerr << "EXP: NUM" << endl;
        #endif
        $$.type = ($1.type == int_) ? int_ : float_; 
        $$.RegNum = currentScopeRegsNum++; 
        $$.name = $1.name; 

        if ($$.type == float_) {
            buffer->emit("COPYF F" + to_string($$.RegNum) + " " + $1.name);
        } else { 
            buffer->emit("COPYI I" + to_string($$.RegNum) + " " + $1.name); 
        }
    }
    | CALL
    {
        #if DEBUG_PARSER
        cerr << "EXP: CALL" << endl;
        #endif
        $$ = $1;
    }
    | VA_MATERIALISE
    {
        #if DEBUG_PARSER
        cerr << "EXP: VA_MATERIALISE" << endl;
        #endif
        $$ = $1;
    }
;

NUM:
    INTEGERNUM
    {
        #if DEBUG_PARSER
        cerr << "NUM: INTEGERNUM" << endl;
        #endif
        $$.type = int_;
        //$$.RegNum = currentScopeRegsNum++;
        //if (!isVariadicArgument) {
        //    buffer->emit(string("COPYI I") + to_string($$.RegNum) + string(" ") + $1.name);
        //}
        $$.quad = buffer->nextQuad();
    }
    | REALNUM
    {
        #if DEBUG_PARSER
        cerr << "NUM: REALNUM" << endl;
        #endif
        $$.type = float_;
        //$$.RegNum = currentScopeRegsNum++;
        //buffer->emit(string("COPYF F") + to_string($$.RegNum) + string(" ") + $1.name);
        $$.quad = buffer->nextQuad();
    }
;

CALL:
    ID LPAREN CALL_ARGS RPAREN
    {
        #if DEBUG_PARSER
        cerr << "CALL: ID LPAREN CALL_ARGS RPAREN" << endl;
        #endif

        // 1) CHECK IF FUNCTION EXISTS
        if (functionTable.find($1.name) == functionTable.end()) {
            printSemanticError("Undefined function '" + $1.name + "'");
            // NOTE: Must stop compilation or at least guard further usage
        }
        Function &func = functionTable[$1.name];

        // 2) CHECK # OF ARGUMENTS MATCHES
        if (func.indexNumVAParams == -1) { //not variadic func
            if (func.paramTypes.size() != $3.paramTypes.size()) {
                printSemanticError("incorrect number of arguments of function '" + $1.name + "'");
            }
        }

        for (int i = 0; i < (int)func.paramTypes.size(); i++) {
            if (func.paramTypes[i] != $3.paramTypes[i]) {
                printSemanticError("incompatible argument type for function '" + $1.name + "'");
            }
        }
    
        // Set the flag for variadic arguments
        if (func.indexNumVAParams != -1) { //need to check if needed
            isVariadicArgument = true;
        }
    
        // ALIGN STACK IF NEEDED (4-BYTE)
        int shiftSize = 0;
        if (current_param_offset % 4 != 0) {
            shiftSize = 4 - (current_param_offset % 4);
            buffer->emit("ADD2I I2 I2 " + to_string(shiftSize));
            current_param_offset += shiftSize;
        }

        //SAVE ALL CALLER REGISTERS ON THE STACK
        int totalBytesPushed = 0;
        int floatBaseReg = currentScopeRegsNum++; // Temporary float base register
        buffer->emit("CITOF F2 I2"); // Convert I2 to F2 for float operations
        for (int regID = 0; regID < currentScopeRegsNum; regID++) {
            // Save integer registers
            buffer->emit("STORI I" + to_string(regID) + " I2 " + to_string(totalBytesPushed));
            // Save float registers
            buffer->emit("STORF F" + to_string(regID) + " F2 " + to_string(totalBytesPushed));
            totalBytesPushed += 4; // Each register is 4 bytes
        }
        totalBytesPushed += 4; 

        //STORE PARAMETERS ON THE STACK
        vector<Type> callArgTypes = $3.paramTypes; 
        vector<int>  callArgRegs  = $3.paramRegs;  
        $3.paramRegs.clear();
		$3.paramTypes.clear();
        
        isVariadicArgument = false;

        // ADJUST THE STACK POINTER (I2) FOR ALL THE SPACE WE RESERVED
        buffer->emit("ADD2I I2 I2 " + to_string(totalBytesPushed));
        buffer->emit("ADD2F F2 F2 " + to_string(totalBytesPushed));
        current_param_offset += totalBytesPushed;

        // SET THE FRAME POINTER (I1 = I2)
        buffer->emit("COPYI I1 I2");
        buffer->emit("CITOF F1 I1");

        for (size_t i = 0; i < callArgTypes.size(); i++) {
            int finalReg = callArgRegs[i];
            Type paramType = callArgTypes[i];

            // Calculate the offset for the parameter
            int paramOffset = -8 - (i * 4);

            if (paramType == float_) {
                // Store float parameters
                buffer->emit("STORF F" + to_string(finalReg) + " F1 " + to_string(paramOffset));
            } else {
                // Store integer parameters
                buffer->emit("STORI I" + to_string(finalReg) + " I1 " + to_string(paramOffset));
            }
        }

        // EMIT THE CALL (JLINK). We fill with backpatch 
        functionTable[$1.name].callingLines.push_back(buffer->nextQuad());
        buffer->emit("JLINK ");

        // ON RETURN: RESTORE THE STACK FRAME (I2 = I1)
        buffer->emit("COPYI I2 I1");
        buffer->emit("CITOF F2 I2");

        // 8) LOAD THE RETURN VALUE (IF NOT void)
        $$.type = func.returnType;
        $$.RegNum = currentScopeRegsNum++;
        if ($$.type != void_t) {
            if ($$.type == float_) {
                // Convert I1 to a float register for float return values
                //int floatBaseReg = currentScopeRegsNum++;
                //buffer->emit("CITOF F1 I1");
                buffer->emit("LOADF F" + to_string($$.RegNum) + " F1 -4");
            } else {
                // Load integer return value directly
                buffer->emit("LOADI I" + to_string($$.RegNum) + " I1 -4");
            }
        }

        // DEALLOCATE THE SPACE WE ADDED
        buffer->emit("SUBTI I2 I2 " + to_string(totalBytesPushed));
        buffer->emit("SUBTF F2 F2 " + to_string(totalBytesPushed));

        // RESTORE ALL CALLER REGISTERS
        int restoreOffset = 0;
        for (int regID = 0; regID < currentScopeRegsNum; regID++) {
            // skip I2
            if (regID == 2) {
                restoreOffset +=4;
                continue;
            }
            buffer->emit("LOADI I" + to_string(regID) +
                         " I2 " + to_string(restoreOffset));
            buffer->emit("LOADF F" + to_string(regID) + " F2 " + to_string(restoreOffset));
            restoreOffset += 4;
        }
        currentScopeRegsNum++;	
    }
;

VA_MATERIALISE:
    VA_ARG LPAREN TYPE COMMA EXP RPAREN
    {
        #if DEBUG_PARSER
        cerr << "VA_MATERIALISE: VA_ARG LPAREN TYPE COMMA EXP RPAREN" << endl;
        #endif
        $$.quad = buffer->nextQuad();
        $$.type = $3.type;
        $$.RegNum = currentScopeRegsNum++;
        std::vector<int> runtime_errors;

        if (!inVariadicFunction)
        {
            printSemanticError("va_arg found in non-variadic function");
        }

        // Get n (offset to n was saved in I3 in function definition).
        int num_va_params_reg = currentScopeRegsNum++;
        buffer->emit("LOADI I" + to_string(num_va_params_reg) + " I1 I3");

        // Runtime check: 0 <= index < n
        int tempReg1 = currentScopeRegsNum++;
        int tempReg2 = currentScopeRegsNum++;

        // Check (index >= 0)
        buffer->emit("SLETI I" + to_string(tempReg1) + " I" + to_string($5.RegNum) + " 0");
        runtime_errors.push_back(buffer->nextQuad());
        buffer->emit("BNEQZ I" + to_string(tempReg1) + " "); // Jump if index < 0

        // Check (index < n)
        buffer->emit("SLETI I" + to_string(tempReg2)
                        + " I" + to_string($5.RegNum)
                        + " I" + to_string(num_va_params_reg));
        runtime_errors.push_back(buffer->nextQuad());
        buffer->emit("BREQZ I" + to_string(tempReg2) + " "); // Jump if index >= n

        int temp_reg_3 = currentScopeRegsNum++;
        int va_param_offset = currentScopeRegsNum++;
        // Get index of argument, turn it into offset.
        buffer->emit("ADD2I I" + to_string(temp_reg_3) + " I" + to_string($5.RegNum) + " 1");
        buffer->emit("MULTI I" + to_string(temp_reg_3) + " I" + to_string(temp_reg_3) + " 4");
        buffer->emit("SUBTI I" + to_string(va_param_offset) + " I3 I" + to_string(temp_reg_3));

        if (int_ == $3.type)
        {
            buffer->emit("LOADI I" + to_string($$.RegNum) + " I1 I" + to_string(va_param_offset));
        }
        else if (float_ == $3.type)
        {
            buffer->emit("CITOF F1 I1");
            buffer->emit("CITOF F" + to_string(va_param_offset) + " I" + to_string(va_param_offset));
            buffer->emit("LOADF F" + to_string($$.RegNum) + " F1 F" + to_string(va_param_offset));
        }
        else
        {
            printSemanticError("Invalid type for variadic argument");
        }

        // Error handling block
        int runtime_error_skip = buffer->nextQuad();
        buffer->emit("UJUMP ");
        int runtime_error_print = buffer->nextQuad();
        buffer->emit("PRNTC 82");   // R
        buffer->emit("PRNTC 117");  // u
        buffer->emit("PRNTC 110");  // n
        buffer->emit("PRNTC 116");  // t
        buffer->emit("PRNTC 105");  // i
        buffer->emit("PRNTC 109");  // m
        buffer->emit("PRNTC 101");  // e
        buffer->emit("PRNTC 32");   //
        buffer->emit("PRNTC 101");  // e
        buffer->emit("PRNTC 114");  // r
        buffer->emit("PRNTC 114");  // r
        buffer->emit("PRNTC 111");  // o
        buffer->emit("PRNTC 114");  // r
        buffer->emit("PRNTC 33");   // !
        buffer->emit("PRNTC 10");   // \n
        buffer->emit("HALT");
        buffer->backpatch(runtime_errors, runtime_error_print);
        $$.nextList.push_back(runtime_error_skip); // Skip if nothing bad happened.
        buffer->backpatch($$.nextList, buffer->nextQuad());
    }
;

CALL_ARGS:
    CALL_ARGLIST
    {
        #if DEBUG_PARSER
        cerr << "CALL_ARGS: CALL_ARGLIST" << endl;
        #endif
		$$.paramTypes = $1.paramTypes;	
		$$.paramRegs = $1.paramRegs;
		$1.paramTypes.clear();
		$1.paramRegs.clear();      
    }
    | /* empty */
    {
        #if DEBUG_PARSER
        cerr << "CALL_ARGS: empty" << endl;
        #endif
    }
;

CALL_ARGLIST:
    CALL_ARGLIST COMMA EXP
    {
        #if DEBUG_PARSER
        cerr << "CALL_ARGS: CALL_ARGLIST COMMA EXP" << endl;
        #endif
        //$$.quad = buffer->nextQuad();
        $$.paramTypes = $1.paramTypes;
        $$.paramRegs = $1.paramRegs;
        $$.paramTypes.push_back($3.type);
        $$.paramRegs.push_back($3.RegNum);
        $1.paramTypes.clear();
	$1.paramRegs.clear();
    }
    | EXP
    {
        #if DEBUG_PARSER
        cerr << "CALL_ARGS: EXP" << endl;
        #endif
        $$.paramTypes.push_back($1.type);
        $$.paramRegs.push_back($1.RegNum);
    }
;

M :
    /* EPSILON */
    {
        $$.quad = buffer->nextQuad();
    }
;


N :
    /* EPSILON */
    {
        $$.nextList.push_back(buffer->nextQuad());
        buffer->emit("UJUMP ");
    }
;
%%

int main(int argc, char* argv[]) {
    // Check number of arguments
    if (argc != 2) {
        cerr << "Operational error: invalid number of arguments" << endl;
        exit(OPERATIONAL_ERROR);
    }

    string inputFileName = argv[1];

    // Check file extension
    size_t lastindex = inputFileName.find_last_of(".");
    if (lastindex == string::npos || inputFileName.substr(lastindex) != ".cmm") {
        cerr << "Operational error: invalid file type. expecting '.cmm' extension" << endl;
        exit(OPERATIONAL_ERROR);
    }

    // Open input file
    extern FILE* yyin;
    yyin = fopen(argv[1], "r");
    if (yyin == NULL) {
        cerr << "Operational error: cannot open input file" << endl;
        exit(OPERATIONAL_ERROR);
    }

    // Initialize buffer
    buffer = new Buffer();

    // Parse input
    if (yyparse() != 0) {
        // Error handling is done in yyerror
        fclose(yyin);
        yylex_destroy();
        delete buffer;
        return 1;
    }

    // Generate header
    string header = "<header>\n";

    // Generate unimplemented functions list
    string uimp = "<unimplemented>";
    for (const auto& func : functionTable) {
        if (func.second.startLineImplementation == -1) {
            uimp += " " + func.first;
            for (int line : func.second.callingLines) {
                uimp += "," + to_string(line);
            }
        }
    }
    header += uimp + "\n";

    // Generate implemented functions list
    string imp = "<implemented>";
    for (const auto& func : functionTable) {
        if (func.second.startLineImplementation != -1) {
            imp += " " + func.first + "," + to_string(func.second.startLineImplementation);
        }
    }
    header += imp + "\n";
    header += "</header>";

    // Add header to beginning of buffer
    buffer->frontEmit(header);

    // Generate output file name
    string outputFileName = inputFileName.substr(0, lastindex) + ".rsk";
    size_t found = outputFileName.find_last_of("/\\");
    if (found != string::npos) {
        outputFileName = outputFileName.substr(found + 1);
    }

    // Write to output file
    ofstream rskFile(outputFileName);
    if (!rskFile.is_open()) {
        cerr << "Operational error: cannot create output file" << endl;
        fclose(yyin);
        yylex_destroy();
        delete buffer;
        exit(OPERATIONAL_ERROR);
    }

    rskFile << buffer->printBuffer();
    rskFile.close();
    fclose(yyin);
    yylex_destroy();

    delete buffer;
    return 0;
}

void yyerror(const char *s) {
    cerr << "Syntax error: '" << yytext << "' in line number " << yylineno << endl;
    exit(SYNTAX_ERROR);
}

int printOperationalError (string err) {
    cerr << "Operational error: " << err << endl;
    exit(OPERATIONAL_ERROR);
}

int printSemanticError (string err) {
    cerr << "Semantic error: " << err << " in line number " << yylineno << endl;
    exit(SEMANTIC_ERROR);
}
